# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-25 07:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('raspberrypi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[(b'Income', b'Income'), (b'Expense', b'Expense'), (b'Transfer', b'Transfer'), (b'BalanceReset', b'BalanceReset')], max_length=127)),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('primary_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_account', to='raspberrypi.Accounts')),
                ('secondary_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary_account', to='raspberrypi.Accounts')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True, null=True)),
                ('modified_at', models.DateField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='transactiontype',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='raspberrypi.UserTags'),
        ),
    ]
