# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-25 08:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('raspberrypi', '0002_auto_20170325_0749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
        migrations.RenameModel(
            old_name='UserTags',
            new_name='UserTag',
        ),
    ]
