# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-25 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raspberrypi', '0003_auto_20170325_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
