# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-26 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('raspberrypi', '0004_auto_20170325_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactiontype',
            name='for_date',
            field=models.DateField(default=datetime.datetime(2017, 3, 26, 11, 35, 8, 241440, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
