# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-26 18:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raspberrypi', '0005_transactiontype_for_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactiontype',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='raspberrypi.UserTag'),
        ),
    ]
